### PR TITLE
Adding maria abbreviation

### PR DESCRIPTION
**Pull request by isccarrasco**
Adding abbreviations for the name of the persons who have MARIA as a
first name.

### CODE REVIEW

**Comment by isccarrasco** [comment]
Using the 2.0.0 version of the library, when calculate the RFC typing MA GLORIA as name, i have an RFC with this format NAVM560329627, but on the SAT document i have NAVG560329621.

Adding the validation of the MA abbreviation on the name and exclude it, this RFC as conformed correctly as the SAT document.

**Comment by isccarrasco** [comment]
@josketres can you help to accept the merge?. thanks.

**Comment by josketres** [comment]
Gracias por el PR! 👍

**Comment by isccarrasco** [comment]
@josketres podrías apoyarme con un release al repo de maven del último PR, para que pueda actualizar a través de maven?

Gracias.

**Comment by josketres** [comment]
Listo! :)

**Pull request merged**
